global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'quantumgrid_dbs'
    static_configs:
      - targets: ['qua-grid-pg:5439', 'qua-grid-mongo:27017', 'qua-grid-cache:6379']
      
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['qua-grid-elasticsearch:9200']
      
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['qua-grid-rabbitmq:15672']

  - job_name: 'quantumgrid_services'
    static_configs:
      - targets: ['host.docker.internal:8080', 'host.docker.internal:8081']