name: qua-grid
services:
  pg:
    container_name: qua-grid-pg
    hostname: qua-grid-pg
    image: postgres:16
    environment:
      - 'POSTGRES_DB=quantumgrid'
      - 'POSTGRES_PASSWORD=P4ssword!'
      - 'POSTGRES_USER=quantumgrid'
    ports:
      - '5439:5432'
    volumes:
      - ../scripts/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    networks:
      - quantumgrid-dev

  mongo:
    container_name: qua-grid-mongo
    hostname: qua-grid-mongo
    image: mongo:6.0
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=quantumgrid'
      - 'MONGO_INITDB_ROOT_PASSWORD=P4ssword!'
    ports:
      - '27917:27017'
    volumes:
      - ../scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - quantumgrid-dev

  cache:
    container_name: qua-grid-cache
    hostname: qua-grid-cache
    image: redis:7
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL'
    ports:
      - '6379:6379'
    networks:
      - quantumgrid-dev

  mailpit:
    container_name: qua-grid-mailpit
    hostname: qua-grid-mailpit
    image: axllent/mailpit
    ports:
      - '8025:8025'
      - '1025:1025'
    environment:
      - 'MP_MAX_MESSAGES=5000'
      - 'MP_SMTP_AUTH_ACCEPT_ANY=1'
      - 'MP_SMTP_AUTH_ALLOW_INSECURE=1'
    networks:
      - quantumgrid-dev

  elasticsearch:
    container_name: qua-grid-elasticsearch
    hostname: qua-grid-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - quantumgrid-dev

  logstash:
    container_name: qua-grid-logstash
    hostname: qua-grid-logstash
    image: docker.elastic.co/logstash/logstash:8.9.0
    volumes:
      - ../config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - ELASTICSEARCH_HOST=http://qua-grid-elasticsearch:9200
      - COMPOSE_PROJECT_NAME=qua-grid
      - xpack.monitoring.elasticsearch.hosts=http://qua-grid-elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - quantumgrid-dev

  kibana:
    container_name: qua-grid-kibana
    hostname: qua-grid-kibana
    image: docker.elastic.co/kibana/kibana:8.9.0
    environment:
      - ELASTICSEARCH_HOSTS=http://qua-grid-elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - quantumgrid-dev

  minio:
    container_name: qua-grid-minio
    hostname: qua-grid-minio
    image: minio/minio
    environment:
      - 'MINIO_ROOT_USER=quantumgrid'
      - 'MINIO_ROOT_PASSWORD=P4ssword!'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"
    networks:
      - quantumgrid-dev

  rabbitmq:
    container_name: qua-grid-rabbitmq
    hostname: qua-grid-rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=quantumgrid
      - RABBITMQ_DEFAULT_PASS=P4ssword!
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - quantumgrid-dev

volumes:
  esdata:
    driver: local
  miniodata:
    driver: local
  rabbitmqdata:
    driver: local

networks:
  quantumgrid-dev:
    driver: bridge
